"""Create wallet_links table

Revision ID: ae1512ad27f1
Revises: 
Create Date: 2025-03-02 23:42:32.170980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1512ad27f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_links',
    sa.Column('solana_address', sa.String(), nullable=False),
    sa.Column('eth_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('solana_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_links')
    # ### end Alembic commands ###
